### ISSUE TITLE
r_web_dir shouldn't assume ~ home folder will be used

### ISSUE THREAD

**Issue by attackant** [jplew/SyncDB#16]
I am trying to deploy to a folder outside of my SSH users home directory:

`/var/www/mysite.com/public_html`

This script seems to only work if the target folder in side the user's home folder. Is that correct or am I missing something? 

Why not simply allow the user to choose the full path to the deployment folder?

**Comment by henscu** [comment]
I think jplew is busy on other stuff... If so, perhaps we should make these changes and submit a pull request...

**Comment by attackant** [comment]
This has already been done: https://github.com/ericstroo/SyncDB

Jplew can either merge it or not.

**Comment by henscu** [comment]
Great, thanks for letting me know!
