### ISSUE TITLE
Reset's wordpress installation after running your script

### ISSUE THREAD

**Issue by aadesh** [jplew/SyncDB#2]
I had to make some modifications to your syncdb file to accomodate change in file names and paths. After executing your script, when I visit the url, it asks me to install the wordpress again!!! 

Could you tell me why this is happening?

Below is the change I made.

searchScriptName=srdb.class.php
cliScriptName=srdb.cli.php

searchScriptPath=https://raw.github.com/interconnectit/Search-Replace-DB/master/srdb.class.php
cliScriptPath=https://raw.github.com/interconnectit/Search-Replace-DB/master/srdb.cli.php

**Comment by jplew** [comment]
Hi @aadesh, sorry you've been having problems. The problem is, in the new Search and Replace CLI script they changed the flag for the hostname, so the old command stopped working.

SyncDB was just updated to take advantage of version 3, so whenever you get the chance please try it again. Cheers.
