### ISSUE TITLE
Use /bin/bash rather than /bin/sh

### ISSUE THREAD

**Issue by markchitty** [jplew/SyncDB#3]
Hi,

Many thanks for the script - I'm hoping it's going to be a useful deployment tool for me :)

I've just tried running the script on my [VVV vagrant](https://github.com/Varying-Vagrant-Vagrants/VVV) VM and it failed. With some [help](http://askubuntu.com/questions/141928/what-is-difference-between-bin-sh-and-bin-bash) I figured out that /bin/sh on an Ubuntu machine points to dash rather than bash. Changing the first line from `#!/bin/sh` to `#!/bin/bash` solved the problem. According to the article, this will work on non-Ubuntu servers as well so should be a safe cross-platform change.

**Comment by jplew** [comment]
thanks for the tip, I fixed it. I myself just switched to a Digital Ocean Ubuntu droplet and was experiencing the same problem. I haven't tested on any CentOS servers yet, but if you run into any more problems please let me know..
