### ISSUE TITLE
Documentation Correction line 87 for rsync_pull and rsync_push

### ISSUE THREAD

**Issue by Steve-Roderick** [jplew/SyncDB#6]
Hi,

I want to write in all Caps how amazing this script is - Thank you so much for sharing.

I was hoping you could make a correction to the internal documentation of SyncDB. I would submit a pull request but it's adding one character on line 87 of the syncdb script.

```
...
82 # $l_upload_dir and $r_upload_dir are where your site's 'uploads' folder are
83 # located. This tells rsync which directories on your FTP should be
84 # synchronized. If you're using WP-Skeleton
85 # <http://markjaquith.wordpress.com/2012/05/26/wordpress-skeleton/>, all you
86 # have to synchronize is your shared folder (content/uploads is symlinked to
-- 87 # shared/content/uploads). Otherwise, it's probably wp-content/uploads.
...
++ 87 # shared/content/uploads). Otherwise, it's probably wp-content/uploads/.
```

Please note the final slash on line ++87. Without the final slash  - the folders are synchronized to the wrong locations.

Thanks again JP - you are legend.

**Comment by jplew** [comment]
fixed! Thanks Yeow-Meng for finding that, and for your nice feedback. :)
