### ISSUE TITLE
Ftp only

### ISSUE THREAD

**Issue by kyleharvey152** [jplew/SyncDB#9]
Hi! My website is currently on a shared server that doesn't support ssh. Is there any way to use syncdb with just ftp?

**Comment by jplew** [comment]
Hi Kyle:
unfortunately, no. I can't see any way for the script to work without ssh presently. Thanks. -JP

**Comment by kyleharvey152** [comment]
Guess I'll just have to upgrade to a better server. Thanks!

**Comment by jplew** [comment]
in the meantime, you may want to give the WP Migrate Pro plugin a try. I haven't used it but I hear it doesn't require SSH and works well

**Comment by kyleharvey152** [comment]
Thanks for the suggestion, I'll check it out.

Kyle
